zephyrproject-rtos/gsoc-2022-arduino-core

samples/threads_arduino/CMakeLists.txt
The CMakelists file did not specify the overlay and hence the nodes in the header files were nowhere to be found.
This commit fixes the issue by adding the overlay file, and also adds other flags that help eliminate unused var warnings
=> samples: threads: fix build errors

cores/arduino/zephyrCommon.cpp
Wraps Zephyr kernel timing calls in Arduino API. This completes the Arduino Time functions.
=> Add micros() and millis() functions

cores/arduino/zephyrCommon.cpp
* Fixes https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/issues/40
* yield(): causes the current thread to yield execution to another thread of the same or higher priority.
If there are no other ready threads of the same or higher priority, the routine returns immediately.
* Also replace include Arduino "" with <>.
=> zephyrCommon: Implement yield()

README.md, documentation/arduino_libs.md, documentation/variants.md
=> start writing Documentation

README.md, install.sh
Installing this module will become a lot easier, the user just has to run this script and start using the module!
=> create install script for linux

variants/arduino_mkrzero/arduino_mkrzero.overlay, variants/arduino_mkrzero/arduino_mkrzero_pinmap.h, variants/variants.h
Adds support for the arduino mkr zero board. Tested with LED_Blink sample.
I am not sure about the inbuilt LED pin number though, hence this pinmap just uses D7 for
demo purposes
=> variants: add support for arduino_mkrzero

cores/arduino/Arduino.h, variants/arduino_nano_33_ble/arduino_nano_33_ble_pinmap.h, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense_pinmap.h, variants/arduino_nano_33_iot/arduino_nano_33_iot_pinmap.h, variants/nrf52840dk_nrf52840/nrf52840dk_nrf52840_pinmap.h
Also fix https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/issues/47
=> variants: bunch all includes in common file

.checkpatch.conf, .github/license_config.yml, .github/workflows/checkpatch.yml, .github/workflows/license_check.yml
Sets up a workflow that will take care of code formatting in PRs
=> workflow: setup checkpatch workflow

variants/arduino_nano_33_iot/arduino_nano_33_iot_pinmap.h
Use arduino_nano_i2c instead of i2c0.
Signed-off-by: TOKITA Hiroshi <tokita.hiroshi@fujitsu.com>
=> variants: arduino_nano_33_iot: Fix 'i2c0' fail to resolve

variants/arduino_mkrzero/arduino_mkrzero.overlay, variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay
Fix this warnings
```
unit address and first address in 'reg' (0xa) don't match for /soc/adc@42004000/channel@10
unit address and first address in 'reg' (0xb) don't match for /soc/adc@42004000/channel@11
unit address and first address in 'reg' (0x12) don't match for /soc/adc@42004000/channel@18
unit address and first address in 'reg' (0x13) don't match for /soc/adc@42004000/channel@19
```
```
unit address and first address in 'reg' (0x6a) don't match for /soc/sercom@42001800/atecc608a@15
```
may be problem in `boards/arm/arduino_nano_33_iot/arduino_nano_33_iot.dts`
=> variants: arduino_nano_33_iot: describe unit address in hex

documentation/variants.md, libraries/Wire/Wire.cpp, libraries/Wire/Wire.h, variants/arduino_mkrzero/arduino_mkrzero.overlay, variants/arduino_mkrzero/arduino_mkrzero_pinmap.h, variants/arduino_nano_33_ble/arduino_nano_33_ble.overlay, variants/arduino_nano_33_ble/arduino_nano_33_ble_pinmap.h, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense.overlay, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense_pinmap.h, variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay, variants/arduino_nano_33_iot/arduino_nano_33_iot_pinmap.h, variants/nrf52840dk_nrf52840/nrf52840dk_nrf52840_pinmap.h
Instaintiate Wire with i2c device that defined in 'i2cs' array
under zephyr,user node.
If 'i2cs' array is not defined, tries to instantiate with
i2c device that labeled as 'arduino_i2c'.
As a result of apply new rule, the i2c_dev that declared in pinmap.h
is no more used, remove it.
=> libraries: Wire: Instantiate Wire following dts configuration

documentation/variants.md, variants/arduino_mkrzero/arduino_mkrzero.overlay, variants/arduino_nano_33_ble/arduino_nano_33_ble.overlay, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense.overlay, variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay, variants/nrf52840dk_nrf52840/nrf52840dk_nrf52840.overlay, variants/variants.h
The `d0-gpios` node format makes it difficult to handle
digital pin configuration from DTS macros.
Introduce the simple array `digital-pins` instead of `g0-gpios` to define digital pin
to GPIO port and pin mapping.
=> variants: Introduce a digital-pins array to define digital pin

documentation/variants.md, variants/arduino_mkrzero/arduino_mkrzero.overlay, variants/arduino_mkrzero/arduino_mkrzero_pinmap.h, variants/arduino_nano_33_ble/arduino_nano_33_ble.overlay, variants/arduino_nano_33_ble/arduino_nano_33_ble_pinmap.h, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense.overlay, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense_pinmap.h, variants/arduino_nano_33_iot/arduino_nano_33_iot_pinmap.h, variants/nrf52840dk_nrf52840/nrf52840dk_nrf52840_pinmap.h, variants/variants.h
Introduce the `builtin-led-gpios` node to make possible to configuring
the builtin-led from dts.
This node uses to determine the value of the `LED_BUILTIN` macro.
Use the `led0` alias to determine the `LED_BUILTIN` if the `builtin-led-gpios`
is not defined.
The behavior can override by defining the `LED_BUILTIN` in pinmap.h.
It uses definitions that are defined in the header preferentially.
---
The PR is contineued from #60.
I will rebase if #60 merged.
=> variants: Introduce the builtin-led-gpios node

.github/workflows/build.yml
Creates a CI CD workflow to build the next branch for every push  / pull request.
This will ensure that the next branch always builds and is in a build-able state. Thus just before merging into main we will have public record of the module being built.
=> CI/CD: setup docker image build check

cores/arduino/zephyrCommon.cpp, documentation/variants.md, variants/arduino_mkrzero/arduino_mkrzero.overlay, variants/arduino_nano_33_ble/arduino_nano_33_ble.overlay, variants/arduino_nano_33_ble_sense/arduino_nano_33_ble_sense.overlay, variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay, variants/nrf52840dk_nrf52840/nrf52840dk_nrf52840.overlay, variants/variants.h
Change to use GPIO cells to assign PWM and ADC pins.
This change makes it easier to manage because unifying
the notation with `digital-pin-gpios`.
Deleting `pwm-pins` and `io-channel-pins` nodes, and create
`pwm-pin-gpios` and `adc-pins-gpios`.
=> GPIO cells use to PWM and ADC pin assigning

variants/cc3220sf_launchxl/cc3220sf_launchxl.overlay, variants/cc3220sf_launchxl/cc3220sf_launchxl_pinmap.h, variants/variants.h
Add support for the TI [CC3220SF LaunchXL](https://www.ti.com/product/CC3200#software-development) platform
Closes https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/issues/35
=> variants: Add cc3220sf

README.md, samples/analog_input/CMakeLists.txt, samples/attach_interrupt/CMakeLists.txt, samples/blinky_arduino/CMakeLists.txt, samples/button_press_led/CMakeLists.txt, samples/fade/CMakeLists.txt, samples/hello_arduino/CMakeLists.txt, samples/i2cdemo/CMakeLists.txt, samples/serial_event/CMakeLists.txt, samples/threads_arduino/CMakeLists.txt, variants/cc3220sf_launchxl/cc3220sf_launchxl.overlay, variants/cc3220sf_launchxl/cc3220sf_launchxl_pinmap.h, variants/nrf9160dk_nrf9160/nrf9160dk_nrf9160.overlay, variants/nrf9160dk_nrf9160/nrf9160dk_nrf9160_pinmap.h, variants/variants.h
A lot of new additions this time,
* Adds support for TI-CC3220SF LaunchXL
*  [Add support for nRF9160](https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/commit/976925a6074b2eca7942f9f03742624acd9a274e)
* [samples: Fix paths to overlay files given to cmake on Windows](https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/commit/bcfd8baaa1eae7f919f6cb81b6e6c2ba9f16b6b7)
=> Request to pull in changes for Aug 2023

cores/arduino/zephyrSerial.cpp, cores/arduino/zephyrSerial.h
DT_NODE_EXISTS value is true even if the status is disabled, so it caused misdetection.
Use DT_NODE_HAS_STATUS to detect the status of
the arduino_serial1 node is ok.
Fix #77
=> zephyrSerial: Fix misdetection arduino_serial1

cores/arduino/zephyrSerial.cpp, cores/arduino/zephyrSerial.h
=> [Re] zephyrSerial: Fix misdetection arduino_serial1

documentation/variants.md, variants/beagleconnect_freedom/beagleconnect_freedom.overlay, variants/beagleconnect_freedom/variants.h
- Test blinky_arduino
- Test hello_arduino
Not sure how I should number the mikrobus digital pins (or if I even should).
=> Add support for beagleconnect_freedom

variants/beagleconnect_freedom/beagleconnect_freedom.overlay, variants/beagleconnect_freedom/variants.h
- Add pin layout described here: https://openbeagle.org/beagleconnect/zephyr/arduino-core/-/commit/1ce0b0bfca16ffc9eb781f263525347e0b42cef5
- Also remove LED_BUILTIN. Seems the dts entry is sufficient.
=> beagleconnect_freedom: Add digital, analog, pwm pins
